#!/usr/bin/env python

import os
import sys
import json
import ruamel.yaml
import base64

data=json.load(sys.stdin)

if len(sys.argv) > 1:
    rootdir=sys.argv[1]
else:
    rootdir=data["name"]
print(f'Creating chart dir: {rootdir}')
os.makedirs(rootdir)

def save_file(name, content, yaml=False):
    print(f'Creating file: {rootdir}/{name}')
    with open(rootdir + '/' + name, 'w') as f:
        if yaml and content is not None:
            content=ruamel.yaml.dump(content, Dumper=ruamel.yaml.RoundTripDumper)
            f.write('# Auto-generated by helm-recreate.py: \n')
        if content is None:
            content = ''
        f.write(content)

save_file('Chart.yaml', data["chart"]["metadata"], yaml=True)
save_file('values.yaml', data["chart"].get("values", None), yaml=True)

for template in data["chart"]["templates"]:
    data=base64.b64decode(template["data"]).decode("utf-8")
    filename=template["name"]
    dirname=os.path.dirname(filename)
    try:
        os.makedirs(rootdir + '/' + dirname)
    except FileExistsError:
        pass

    save_file(filename, data)
